name: flutter_cache_manager
description: Flutter Cache Manager is a Utility package built with Flutter SDK and SQLite Package. 
version: 1.0.0
homepage: https://www.youtube.com/SnippetCoder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

